import pytest
import jax
import jax.numpy as jnp
from jepa_robotics.models.v_jepa import ViTEncoder, JEPAPredictor
from jepa_robotics.models.world_model import ActionConditionedTransformer
from jepa_robotics.training.optimization import build_smac_scenario


# ── Shared geometry for tests ────────────────────────────────────────────────
BATCH_SIZE = 2
IMAGE_SIZE = 256
LATENT_DIM = 128
PATCH_SIZE = 32
MASKING_RATIO = 0.75

NUM_PATCHES = (IMAGE_SIZE // PATCH_SIZE) ** 2   # 64
NUM_TARGET = int(NUM_PATCHES * MASKING_RATIO)    # 48
NUM_CONTEXT = NUM_PATCHES - NUM_TARGET           # 16


def test_vit_encoder_target_path_shape():
    """Target encoder (no mask): must return latents for ALL patches + correct pooled shape."""
    mock_image = jnp.ones((BATCH_SIZE, IMAGE_SIZE, IMAGE_SIZE, 3))

    encoder = ViTEncoder(latent_dim=LATENT_DIM, depth=2, num_heads=4, patch_size=PATCH_SIZE)

    rng = jax.random.PRNGKey(0)
    variables = encoder.init({'params': rng}, mock_image)

    patch_latents, pooled = encoder.apply(variables, mock_image)

    # Target path: all patches returned
    assert patch_latents.shape == (BATCH_SIZE, NUM_PATCHES, LATENT_DIM), (
        f"Expected ({BATCH_SIZE}, {NUM_PATCHES}, {LATENT_DIM}), got {patch_latents.shape}"
    )
    assert pooled.shape == (BATCH_SIZE, LATENT_DIM), (
        f"Expected ({BATCH_SIZE}, {LATENT_DIM}), got {pooled.shape}"
    )


def test_vit_encoder_context_path_shape():
    """Context encoder (with mask): must return latents only for the context subset."""
    mock_image = jnp.ones((BATCH_SIZE, IMAGE_SIZE, IMAGE_SIZE, 3))

    encoder = ViTEncoder(latent_dim=LATENT_DIM, depth=2, num_heads=4, patch_size=PATCH_SIZE)

    rng = jax.random.PRNGKey(0)
    variables = encoder.init({'params': rng}, mock_image)

    # Simulate the context indices that would be generated by generate_patch_mask
    context_indices = jnp.arange(NUM_CONTEXT)  # (N_context,) — static shape
    patch_latents, pooled = encoder.apply(variables, mock_image, patch_indices=context_indices)

    # Context path: only N_context patches returned
    assert patch_latents.shape == (BATCH_SIZE, NUM_CONTEXT, LATENT_DIM), (
        f"Expected ({BATCH_SIZE}, {NUM_CONTEXT}, {LATENT_DIM}), got {patch_latents.shape}"
    )
    assert pooled.shape == (BATCH_SIZE, LATENT_DIM)


def test_jepa_predictor_output_shape():
    """Predictor must output predictions for exactly N_target patches."""
    mock_context_latents = jnp.ones((BATCH_SIZE, NUM_CONTEXT, LATENT_DIM))
    mock_target_pos_emb = jnp.ones((BATCH_SIZE, NUM_TARGET, LATENT_DIM))

    predictor = JEPAPredictor(latent_dim=LATENT_DIM, depth=2, num_heads=4)
    rng = jax.random.PRNGKey(0)
    variables = predictor.init(rng, mock_context_latents, mock_target_pos_emb)

    predictions = predictor.apply(variables, mock_context_latents, mock_target_pos_emb)

    assert predictions.shape == (BATCH_SIZE, NUM_TARGET, LATENT_DIM), (
        f"Expected ({BATCH_SIZE}, {NUM_TARGET}, {LATENT_DIM}), got {predictions.shape}"
    )


def test_world_model_causal_masking_and_shape():
    """Verify the Action-Conditioned Transformer compiles and outputs next states."""
    batch_size = 2
    seq_len = 5
    latent_dim = 256
    action_dim = 7

    mock_latents = jnp.ones((batch_size, seq_len, latent_dim))
    mock_actions = jnp.ones((batch_size, seq_len, action_dim))

    world_model = ActionConditionedTransformer(latent_dim=latent_dim, action_dim=action_dim, depth=2)

    rng = jax.random.PRNGKey(0)
    variables = world_model.init(rng, mock_latents, mock_actions)

    next_state_preds = world_model.apply(variables, mock_latents, mock_actions)

    assert next_state_preds.shape == (batch_size, seq_len, latent_dim)


def test_smac3_scenario_builds_correctly():
    """Verify the updated ConfigSpace is SOTA: correct ranges, forbidden clauses, no legacy params."""
    scenario = build_smac_scenario()
    cs = scenario.configspace

    # Core hyperparameters present
    assert "latent_dim" in cs
    assert "vit_depth" in cs
    assert "tau" in cs
    assert "masking_ratio" in cs
    assert "sigreg_weight" in cs
    assert "num_heads" in cs

    # Legacy params removed
    assert "use_masking" not in cs

    # patch_size=64 must be absent (degenerate with true masking)
    patch_hp = cs["patch_size"]
    assert 64 not in patch_hp.choices, "patch_size=64 should be removed (only 16 patches total)"

    # num_heads must include 16 for latent_dim=512 coverage
    heads_hp = cs["num_heads"]
    assert 16 in heads_hp.choices

    # weight_decay default must be in SOTA ViT range (>= 0.01)
    wd_hp = cs["weight_decay"]
    assert wd_hp.default_value >= 0.01, "weight_decay default below SOTA ViT range"

    # Forbidden clause must be registered: (latent_dim=128, num_heads=16)
    forbidden_combos = cs.forbidden_clauses
    assert len(forbidden_combos) >= 1, "Missing forbidden clause for (latent_dim=128, num_heads=16)"


def test_sigreg_loss_near_zero_for_isotropic_gaussian():
    """SIGReg loss should be very small when latents are already N(0, I)."""
    from jepa_robotics.training.step import sigreg_loss

    rng = jax.random.PRNGKey(42)
    rng, data_rng, sketch_rng = jax.random.split(rng, 3)

    # Draw a large batch from a true isotropic Gaussian
    latents = jax.random.normal(data_rng, (512, LATENT_DIM))
    loss = sigreg_loss(latents, sketch_rng, num_sketches=128)

    # Loss should be close to zero (small statistical noise only)
    assert float(loss) < 0.1, f"SIGReg loss on N(0,I) samples too high: {float(loss):.4f}"


def test_sigreg_loss_large_for_collapsed_representation():
    """SIGReg loss should be large when the representation has collapsed (constant latents)."""
    from jepa_robotics.training.step import sigreg_loss

    rng = jax.random.PRNGKey(7)
    rng, sketch_rng = jax.random.split(rng)

    # Simulate dimensional collapse: all vectors identical (zero variance, non-zero mean)
    collapsed_latents = jnp.ones((64, LATENT_DIM)) * 5.0
    loss = sigreg_loss(collapsed_latents, sketch_rng, num_sketches=64)

    # Loss should be large — mean is 5.0 (not 0), variance is 0 (not 1)
    assert float(loss) > 10.0, f"SIGReg loss on collapsed latents too low: {float(loss):.4f}"
